version: '3.8'

services:
  auth-service:
    image: dilshaan/budget-planner-auth:latest
    container_name: budget-planner-auth
    ports:
      - "5001:5001"
    environment:
      - DEBUG=true
      - SECRET_KEY=demo-secret-key
      - PORT=5001
    networks:
      - budget-planner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  budget-service:
    image: dilshaan/budget-planner-budget:latest
    container_name: budget-planner-budget
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true
      - SECRET_KEY=demo-secret-key
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth-service:5001
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/budget_planner?authSource=admin
    depends_on:
      - auth-service
      - mongodb
    networks:
      - budget-planner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7.0
    container_name: budget-planner-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=budget_planner
    volumes:
      - mongodb_data:/data/db
      - ./mongo_db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - budget-planner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  budget-planner-network:
    driver: bridge

