apiVersion: v1
kind: Service
metadata:
  name: budget-nodeport
  namespace: budget-planner
  labels:
    app: budget-service
spec:
  type: NodePort
  selector:
    app: budget-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
    name: http


