apiVersion: v1
kind: Service
metadata:
  name: budget-service
  namespace: budget-planner
  labels:
    app: budget-service
spec:
  selector:
    app: budget-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP


