apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-deployment
  namespace: budget-planner
  labels:
    app: budget-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-service
  template:
    metadata:
      labels:
        app: budget-service
    spec:
      containers:
      - name: budget-service
        image: dilshaan/budget-planner-budget:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:5001"
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongo-uri
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
