apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: budget-planner
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongodb
  type: ClusterIP
