apiVersion: v1
kind: Service
metadata:
  name: auth-nodeport
  namespace: budget-planner
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30001
    name: http


